on:
  push:
    branches:
      - master
      - feature/github_actions

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os-arch: aarch64
    env:
      CROSS_SYSROOT: /mnt/alpine-${{ matrix.os-arch }}
    steps:
      - uses: actions/checkout@v1

      - name: Set up Alpine Linux for ${{ matrix.os-arch }} (target arch)
        id: alpine-target
        uses: jirutka/setup-alpine@v1
        with:
          arch: ${{ matrix.os-arch }}
          branch: latest-stable
          packages: >
            build-base
            alpine-sdk
            cmake
            g++
          shell: alpine.sh {0}

      - name: Build C++ application with CMake
        run: cmake -B build && cmake --build build --config Release
        shell: alpine.sh {0}

      - name: Try to run the binary
        run: ./build/helloworld
        shell: alpine.sh {0}

      - name: Generate private key
        run: abuild-keygen -an
        shell: alpine.sh {0}

      - name: Create APK package directory structure
        run: |
          mkdir -p package/helloworld
          mv build/helloworld package/helloworld/
          echo "pkgname=helloworld" >> package/helloworld/APKBUILD
          echo "pkgver=1.0" >> package/helloworld/APKBUILD
          echo "pkgrel=1" >> package/helloworld/APKBUILD
          echo "pkgdesc=\"A simple Hello World program\"" >> package/helloworld/APKBUILD  
          echo "arch=noarch" >> package/helloworld/APKBUILD
          echo "url=\"https://example.com\"" >> package/helloworld/APKBUILD
          echo "license=\"GPL\"" >> package/helloworld/APKBUILD
          echo "depends=" >> package/helloworld/APKBUILD
          echo "" >> package/helloworld/APKBUILD
          echo "package() {" >> package/helloworld/APKBUILD
          echo "    install -Dm755 helloworld \"\$pkgdir\"/usr/bin/helloworld" >> package/helloworld/APKBUILD
          echo "}" >> package/helloworld/APKBUILD
        shell: alpine.sh {0}

      - name: Build APK package
        run: |
          sudo adduser runner abuild
          cd package/helloworld
          abuild checksum
          abuild -r
          pwd
          ls -la
        shell: alpine.sh {0}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
      
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/work/packages/package/aarch64/
          asset_name: helloworld-1.0-r1.apk
          asset_content_type: application/vnd.alpine.package+json
