name: C++ CI

on:
  push:
    branches:
      - master
      - feature/github_actions

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os-arch: aarch64
    env:
      CROSS_SYSROOT: /mnt/alpine-${{ matrix.os-arch }}
    steps:
      - uses: actions/checkout@v1

      - name: Set up Alpine Linux for ${{ matrix.os-arch }} (target arch)
        id: alpine-target
        uses: jirutka/setup-alpine@v1
        with:
          arch: ${{ matrix.os-arch }}
          branch: latest-stable
          packages: >
            build-base
            alpine-sdk
            cmake
            g++
          shell: alpine.sh {0}

      - name: Build C++ application with CMake
        run: cmake -B build && cmake --build build --config Release
        shell: alpine.sh {0}

      - name: Try to run the binary
        run: ./build/helloworld
        shell: alpine.sh {0}

      - name: Generate private key
        run: abuild-keygen -a
        shell: alpine.sh {0}

      - name: Create APK package directory structure
        run: |
          mkdir -p package/helloworld
          mv build/helloworld package/helloworld/
          echo "description=\"A simple Hello World program\"" > package/helloworld/APKBUILD
          echo "pkgname=helloworld" >> package/helloworld/APKBUILD
          echo "pkgver=1.0" >> package/helloworld/APKBUILD
          echo "arch=noarch" >> package/helloworld/APKBUILD
          echo "url=\"https://example.com\"" >> package/helloworld/APKBUILD
          echo "license=\"MIT\"" >> package/helloworld/APKBUILD
          echo "depends=" >> package/helloworld/APKBUILD
          echo "" >> package/helloworld/APKBUILD
          echo "build() {" >> package/helloworld/APKBUILD
          echo "    return 0" >> package/helloworld/APKBUILD
          echo "}" >> package/helloworld/APKBUILD
          echo "" >> package/helloworld/APKBUILD
          echo "package() {" >> package/helloworld/APKBUILD
          echo "    mkdir -p \"\$pkgdir\"" >> package/helloworld/APKBUILD
          echo "    cp -r \"\$srcdir\"/* \"\$pkgdir\"/" >> package/helloworld/APKBUILD
          echo "}" >> package/helloworld/APKBUILD
        shell: alpine.sh {0} 

      - name: Build APK package
        run: |
          cd package/helloworld
          abuild checksum
          abuild -r
        shell: alpine.sh {0}
