name: C++ CI

on:
  push:
    branches:
      - master
      - feature/github_actions
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os-arch: aarch64
    env:
      CROSS_SYSROOT: /mnt/alpine-${{ matrix.os-arch }}
    steps:
      - uses: actions/checkout@v1

      - name: Set up Alpine Linux for ${{ matrix.os-arch }} (target arch)
        id: alpine-target
        uses: jirutka/setup-alpine@v1
        with:
          arch: ${{ matrix.os-arch }}
          branch: edge
          packages: >
            alpine-sdk
            cmake
            g++
          shell-name: alpine-target.sh

      - name: Build C++ application with CMake
        run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain/${{ matrix.os-arch }}.cmake && cmake --build build --config Release

      - name: Try to run the binary
        run: ./build/myapp --version
        shell: alpine-target.sh {0}
