name: C++ CI

on:
  push:
    branches:
      - master
      - feature/github_actions

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os-arch: aarch64
    env:
      CROSS_SYSROOT: /mnt/alpine-${{ matrix.os-arch }}
    steps:
      - uses: actions/checkout@v1

      - name: Print current directory
        run: pwd

      - name: Set up Alpine Linux for ${{ matrix.os-arch }} (target arch)
        id: alpine-target
        uses: jirutka/setup-alpine@v1
        with:
          arch: ${{ matrix.os-arch }}
          branch: edge
          packages: >
            alpine-sdk
            cmake
            g++
          shell-name: alpine-target.sh

      - name: Print current directory
        run: pwd

      - name: Build C++ application with CMake
        run: cmake -B build && cmake --build build --config Release

      - name: Print current directory
        run: pwd

      - name: List contents of the build directory
        run: ls -l build

      - name: Print current directory
        run: pwd

      - name: Try to run the binary
        run:  ./build/helloworld

      - name: Create APK package directory structure
        run: |
          mkdir -p package/helloworld
          mv build/helloworld package/helloworld/
          echo "description=\"A simple Hello World program\"" > package/helloworld/APKBUILD
          echo "pkgname=helloworld" >> package/helloworld/APKBUILD
          echo "pkgver=1.0" >> package/helloworld/APKBUILD
          echo "arch=noarch" >> package/helloworld/APKBUILD
          echo "url=\"https://example.com\"" >> package/helloworld/APKBUILD
          echo "license=\"GPL\"" >> package/helloworld/APKBUILD
          echo "depends=" >> package/helloworld/APKBUILD
          echo "" >> package/helloworld/APKBUILD
          echo "build() {" >> package/helloworld/APKBUILD
          echo "    return 0" >> package/helloworld/APKBUILD
          echo "}" >> package/helloworld/APKBUILD
          echo "" >> package/helloworld/APKBUILD
          echo "package() {" >> package/helloworld/APKBUILD
          echo "    mkdir -p \"\$pkgdir\"" >> package/helloworld/APKBUILD
          echo "    cp -r \"\$srcdir\"/* \"\$pkgdir\"/" >> package/helloworld/APKBUILD
          echo "}" >> package/helloworld/APKBUILD


      - name: Build APK package
        run: |
          cd package/helloworld
          pwd
          abuild checksum
          abuild -r
        
