name: C++ CI

on:
  push:
    branches:
      - master
      - feature/github_actions

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os-arch: aarch64
    env:
      CROSS_SYSROOT: /mnt/alpine-${{ matrix.os-arch }}
    steps:
      - uses: actions/checkout@v1

      - name: Print current directory
        run: pwd

      - name: Set up Alpine Linux for ${{ matrix.os-arch }} (target arch)
        id: alpine-target
        uses: jirutka/setup-alpine@v1
        with:
          arch: ${{ matrix.os-arch }}
          branch: edge
          packages: >
            alpine-sdk
            cmake
            g++
          shell-name: alpine-target.sh

      - name: Print current directory
        run: pwd

      - name: Build C++ application with CMake
        run: cmake -B build && cmake --build build --config Release

      - name: Print current directory
        run: pwd

      - name: List contents of the build directory
        run: ls -l build

      - name: Print current directory
        run: pwd

      - name: Try to run the binary
        run:  ./build/helloworld
        
